### ISSUE TITLE
Reference original jasmine-utils library

### ISSUE THREAD

**Issue by mjeanroy** [geoffdutton/karma-jasmine-utils#1]
Hi,

Would you be open for a pull request referencing the [original jasmine-utils](https://www.npmjs.com/package/jasmine-utils) library instead of your fork? If not, what features do you use that are missing (I'll be happy to implement this)?

**Comment by geoffdutton** [comment]
Sure, I would be open to a pull request. I will look to see if I’m using any features that are specific to my fork. I had implemented a couple, but after a year of real world use, I don’t think I’m using them, or haven’t been using them.

**Comment by geoffdutton** [comment]
All right it's published to npm as v1.3.0 https://www.npmjs.com/package/karma-jasmine-utils
